name: toreyheinz
favicon: null
layout_spectrum: 0.9684614930301905
typography_spectrum: 0.8567145690321922
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8352337907999754
  lightness: 0.22008429490961134
  saturation: 0.7093157463241369
  rhythmicContrast: 0.18815341219305992
purpose: []
